### ISSUE TITLE
Timeout is not properly displayed on Kids layout

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-laboratory#967]

**Comment by julian-berbel** [comment]
Fixed by https://github.com/mumuki/mumukit-bridge/commit/1b0e6f959ff65c8f2e1ea027c50a98e397e61fc9.

**Comment by flbulgarelli** [comment]
This is still happening. 

![image](https://user-images.githubusercontent.com/677436/38640134-c8fdb526-3da9-11e8-9eeb-8f9f108905a7.png)


I suggest to also implement a string check for the `Timed out reading data from server` result.

**Comment by flbulgarelli** [comment]
We should path responses with `"Timed out reading data from server"` as `aborted`.

**Comment by flbulgarelli** [comment]
So, in the end the problem is just with the kids layout. It is an UI issue, not a backend problem. @fedescarpa please address it.
